open Types[@@ocaml.warning "-33"]
open Aws.BaseTypes[@@ocaml.warning "-33"]
open Aws
module DescribeTypeRegistrationInput =
  struct
    type t =
      {
      registration_token: String.t
        [@ocaml.doc
          "<p>The identifier for this registration request.</p> <p>This registration token is generated by CloudFormation when you initiate a registration request using <code> <a>RegisterType</a> </code>.</p>"]}
    let make ~registration_token  () = { registration_token }
    let to_query v = Query.List (Util.list_filter_opt [])
    let to_headers v = Headers.List (Util.list_filter_opt [])
    let to_json v =
      `Assoc
        (Util.list_filter_opt
           [Some
              ("registration_token", (String.to_json v.registration_token))])
    let parse xml =
      Some
        {
          registration_token =
            (Xml.required "RegistrationToken"
               (Util.option_bind (Xml.member "RegistrationToken" xml)
                  String.parse))
        }
    let to_xml v =
      Util.list_filter_opt
        ([] @
           [Some
              (Ezxmlm.make_tag "RegistrationToken"
                 ([], (String.to_xml v.registration_token)))])
  end
module DescribeTypeRegistrationOutput = DescribeTypeRegistrationOutput
type input = DescribeTypeRegistrationInput.t
type output = DescribeTypeRegistrationOutput.t
type error = Errors_internal.t
let streaming = false
let service = "cloudformation"
let to_http service region req =
  let uri =
    Uri.add_query_params
      (Uri.of_string
         ((Aws.Util.of_option_exn (Endpoints.url_of service region)) ^ "/"))
      (List.append
         [("Version", ["2010-05-15"]);
         ("Action", ["DescribeTypeRegistration"])]
         (Util.drop_empty
            (Uri.query_of_encoded
               (Query.render (DescribeTypeRegistrationInput.to_query req))))) in
  (`POST, uri,
    (Headers.render (DescribeTypeRegistrationInput.to_headers req)), "")
let of_http headers
  (body : [ `String of string  | `Streaming of Piaf.Body.t ]) =
  let ((`String body) : [ `String of string  | `Streaming of Piaf.Body.t ]) =
    body[@@ocaml.warning "-8"] in
  try
    let xml = Ezxmlm.from_string body in
    let resp =
      Util.option_bind
        (Xml.member "DescribeTypeRegistrationResponse" (snd xml))
        (Xml.member "DescribeTypeRegistrationResult") in
    try
      let open Error in
        Util.or_error
          (Util.option_bind resp DescribeTypeRegistrationOutput.parse)
          (BadResponse
             {
               body;
               message =
                 "Could not find well formed DescribeTypeRegistrationOutput."
             })
    with
    | Xml.RequiredFieldMissing msg ->
        let open Error in
          `Error
            (BadResponse
               {
                 body;
                 message =
                   ("Error parsing DescribeTypeRegistrationOutput - missing field in body or children: "
                      ^ msg)
               })
  with
  | Failure msg ->
      let open Error in
        `Error
          (BadResponse { body; message = ("Error parsing xml: " ^ msg) })
let parse_error code err =
  let errors = [] @ Errors_internal.common in
  match Errors_internal.of_string err with
  | Some v ->
      if
        (List.mem v errors) &&
          ((match Errors_internal.to_http_code v with
            | Some x -> x = code
            | None -> true))
      then Some v
      else None
  | None -> None